apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-catalog-reconciler
  namespace: backstage
  labels:
    app: backstage-catalog-reconciler
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: backstage-catalog-reconciler-key-vault
  target:
    name: backstage-catalog-reconciler
    creationPolicy: Owner
  data:
    - secretKey: github-token
      remoteRef:
        key: backstage-catalog-reconciler-github-token
    - secretKey: teams-webhook-url
      remoteRef:
        key: backstage-catalog-reconciler-teams-webhook-url
