apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-catalog-reconciler
  namespace: backstage
  labels:
    app: backstage-catalog-reconciler
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
  annotations:
    azure.workload.identity/client-id: ${backstage_catalog_reconciler_client_id}
    azure.workload.identity/tenant-id: ${platform_tenant_id}
