apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-host-path-volumes
  annotations:
    policies.kyverno.io/title: Disallow hostPath volumes
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-host-path
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - aks-command
                - kube-system
                - flux-system
                - cert-manager
                - external-dns
                - external-secrets
                - kyverno
                - azureserviceoperator-system
                - keda
                - ingress-nginx
                - ingress-nginx-public
                - observability
      validate:
        message: hostPath volumes are not allowed.
        foreach:
          - list: request.object.spec.volumes || []
            deny:
              conditions:
                any:
                  - key: "{{ element.hostPath || '' }}"
                    operator: NotEquals
                    value: ""
