apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-standard-labels
  annotations:
    policies.kyverno.io/title: Require Platform Labels
    policies.kyverno.io/category: Platform Baseline
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-platform-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - aks-command
                - kube-system
                - flux-system
                - cert-manager
                - external-dns
                - external-secrets
                - kyverno
                - azureserviceoperator-system
                - keda
                - ingress-nginx
                - ingress-nginx-public
                - observability
      validate:
        message: Pods must include app, team, costCenter, and dataClassification labels.
        pattern:
          metadata:
            labels:
              app: "?*"
              team: "?*"
              costCenter: "?*"
              dataClassification: "?*"
