apiVersion: platform.example.io/v1alpha1
kind: NamespaceVendingRequest
metadata:
  name: payments-checkout-nonprod
spec:
  team: payments
  product: checkout
  costCenter: cc-payments
  onCallRotationId: pd-payments-primary
  dataClassification: confidential
  environment: nonprod
  regions:
    - swedencentral
  tags:
    owner: payments
    costCenter: cc-payments
    product: checkout
    dataClassification: confidential
    confidentiality: medium
    managedBy: terraform
    repo: edinc/platform-engineering-landing-zone
  namespace:
    name: payments-checkout-nonprod
    clusterEnvironment: nonprod
    entraGroupObjectId: 00000000-0000-0000-0000-000000000001
    serviceAccountName: checkout-api
    resourceQuota:
      cpuRequests: "2000m"
      memoryRequests: 4Gi
      cpuLimits: "4000m"
      memoryLimits: 8Gi
      pods: 50
    egressAllowlist:
      cidrs:
        - 10.30.0.0/16
    azure:
      aksClusterId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-pe-nonprod-platform-sec/providers/Microsoft.ContainerService/managedClusters/aks-pe-nonprod-sec
      acrId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-pe-nonprod-platform-sec/providers/Microsoft.ContainerRegistry/registries/acrpenonprodsec001
      keyVaultSecretIds:
        - /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-pe-nonprod-platform-sec/providers/Microsoft.KeyVault/vaults/kv-pe-nonprod-sec-001/secrets/payments-checkout
      resourceGroupName: rg-pe-nonprod-platform-sec
