apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-runtime
  namespace: backstage
  labels:
    app: backstage
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: confidential
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: platform-key-vault
  target:
    name: backstage-runtime
    creationPolicy: Owner
  data:
    - secretKey: backstage-session-secret
      remoteRef:
        key: backstage-session-secret
    - secretKey: microsoft-auth-client-secret
      remoteRef:
        key: backstage-microsoft-auth-client-secret
    - secretKey: github-app-id
      remoteRef:
        key: backstage-github-app-id
    - secretKey: github-app-client-id
      remoteRef:
        key: backstage-github-app-client-id
    - secretKey: github-app-client-secret
      remoteRef:
        key: backstage-github-app-client-secret
    - secretKey: github-app-webhook-secret
      remoteRef:
        key: backstage-github-app-webhook-secret
    - secretKey: github-app-private-key
      remoteRef:
        key: backstage-github-app-private-key
