apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: platform-key-vault
  namespace: backstage
  labels:
    app: backstage
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://${platform_key_vault_name}.vault.azure.net
      serviceAccountRef:
        name: backstage
        namespace: backstage
