apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backstage-postgres-fallback
  namespace: backstage
  labels:
    app: backstage
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: confidential
spec:
  provider: azure
  secretObjects:
    - secretName: backstage-postgres-fallback
      type: Opaque
      data:
        - objectName: backstage-postgres-password
          key: password
  parameters:
    usePodIdentity: "false"
    clientID: ${backstage_client_id}
    keyvaultName: ${platform_key_vault_name}
    tenantId: ${platform_tenant_id}
    objects: |
      array:
        - |
          objectName: backstage-postgres-password
          objectAlias: password
          objectType: secret
