apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
  annotations:
    azure.workload.identity/client-id: ${backstage_client_id}
