apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: platform-key-vault
  namespace: observability
  labels:
    app: external-secrets
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://${platform_key_vault_name}.vault.azure.net
      tenantId: ${platform_tenant_id}
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
