apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-rightsizing-github
  namespace: observability
  labels:
    app: vpa-rightsizing-reporter
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: platform-key-vault
  target:
    name: platform-rightsizing-github
    creationPolicy: Owner
  data:
    - secretKey: repository
      remoteRef:
        key: platform-rightsizing-github-repository
    - secretKey: token
      remoteRef:
        key: platform-rightsizing-github-token
