apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpa-rightsizing-reporter
  labels:
    app: vpa-rightsizing-reporter
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
rules:
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["verticalpodautoscalercheckpoints", "verticalpodautoscalers"]
    verbs: ["get", "list"]
