apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../_base/controllers
  - namespace-ingress-nginx-public.yaml
  - ingress-nginx-public.yaml
  - ingress-nginx-public-ingressclass-rbac.yaml
  - public-backstage-kustomization.yaml
patches:
  - target:
      kind: HelmRelease
      name: kyverno
    patch: |-
      - op: replace
        path: /spec/values/admissionController/replicas
        value: 1
      - op: replace
        path: /spec/values/backgroundController/replicas
        value: 1
  - target:
      kind: HelmRelease
      name: ingress-nginx
    patch: |-
      - op: replace
        path: /spec/values/controller/replicaCount
        value: 1
  - target:
      kind: HelmRelease
      name: opentelemetry-collector
    patch: |-
      - op: replace
        path: /spec/values/config/processors/tail_sampling/policies/1/probabilistic/sampling_percentage
        value: 100
