apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-public
  labels:
    app: ingress-nginx-public
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
