apiVersion: v1
kind: Namespace
metadata:
  name: azureserviceoperator-system
  labels:
    app: azure-service-operator
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
    platform.example.io/pod-security-exception: aso-chart-pre-upgrade-hook
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
