apiVersion: platform.example.io/v1alpha1
kind: SubscriptionVendingRequest
metadata:
  name: payments-nonprod-subscription
  labels:
    platform.example.io/requester: backstage
spec:
  team: payments
  product: checkout
  costCenter: cc-payments
  onCallRotationId: pd-payments-primary
  dataClassification: confidential
  environment: nonprod
  regions:
    - swedencentral
  tags:
    owner: payments
    costCenter: cc-payments
    product: checkout
    dataClassification: confidential
    confidentiality: medium
    managedBy: terraform
    repo: edinc/platform-engineering-landing-zone
  budget:
    amount: 500
    currency: EUR
    startDate: "2026-07-01T00:00:00Z"
    endDate: "2027-07-01T00:00:00Z"
    contactEmails:
      - platform-finance@example.com
    thresholds:
      - percentage: 80
        type: Actual
      - percentage: 100
        type: Forecasted
  addOns:
    - postgres
    - serviceBus
  subscription:
    mode: create
    archetype: corp
    managementGroupId: corp
    subscriptionAliasName: payments-nonprod
    subscriptionDisplayName: Payments NonProd
    billingScopeId: /providers/Microsoft.Billing/billingAccounts/1234567/enrollmentAccounts/123456
    workload: DevTest
    network:
      addressSpace:
        - 10.64.0.0/20
      hubNetworkResourceId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-pe-nonprod-hub-sec/providers/Microsoft.Network/virtualNetworks/vnet-pe-nonprod-hub-sec
