apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../_base/controllers
patches:
  - target:
      kind: HelmRelease
      name: ingress-nginx
    patch: |-
      - op: replace
        path: /spec/values/controller/replicaCount
        value: 3
  - target:
      kind: HelmRelease
      name: opentelemetry-collector
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 3
