apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-config
  namespace: flux-system
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
  labels:
    app: flux
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
spec:
  dependsOn:
    - name: platform-controllers
  interval: 5m
  path: ./${cluster_state_root_path}/addon-config
  postBuild:
    substitute:
      application_insights_ingestion_endpoint: ${application_insights_ingestion_endpoint}
      aso_client_id: ${aso_client_id}
      azure_dns_resource_group_name: ${azure_dns_resource_group_name}
      backstage_public_ingress_controller_replicas: "${backstage_public_ingress_controller_replicas}"
      backstage_public_ingress_enabled: "${backstage_public_ingress_enabled}"
      backstage_public_ingress_host: "${backstage_public_ingress_host}"
      backstage_public_ingress_public_ip_name: "${backstage_public_ingress_public_ip_name}"
      backstage_public_ingress_resource_group: "${backstage_public_ingress_resource_group}"
      cert_manager_client_id: ${cert_manager_client_id}
      cluster_state_branch: ${cluster_state_branch}
      cluster_state_repository_provider: ${cluster_state_repository_provider}
      cluster_state_repository_url: ${cluster_state_repository_url}
      cluster_state_root_path: ${cluster_state_root_path}
      external_dns_client_id: ${external_dns_client_id}
      external_secrets_client_id: ${external_secrets_client_id}
      github_owner: ${github_owner}
      platform_acr_login_server: ${platform_acr_login_server}
      platform_key_vault_name: ${platform_key_vault_name}
      platform_profile: ${platform_profile}
      platform_repository_name: ${platform_repository_name}
      platform_root_domain: ${platform_root_domain}
      platform_subscription_id: ${platform_subscription_id}
      platform_tenant_id: ${platform_tenant_id}
  prune: true
  retryInterval: 1m
  serviceAccountName: platform-reconciler
  sourceRef:
    kind: GitRepository
    name: platform-cluster-state
  timeout: 10m
  wait: true
