apiVersion: v1
kind: Service
metadata:
  name: {{ include "golden-path.fullname" . }}
  labels:
    {{- include "golden-path.labels" . | nindent 4 }}
  annotations:
    {{- include "golden-path.annotations" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "golden-path.selectorLabels" . | nindent 4 }}
