apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "golden-path.fullname" . }}
  labels:
    {{- include "golden-path.labels" . | nindent 4 }}
  annotations:
    {{- include "golden-path.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "golden-path.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
