{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "golden-path.labels" . | nindent 4 }}
  annotations:
    {{- include "golden-path.annotations" . | nindent 4 }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentityClientId | quote }}
    platform.example.io/on-call: {{ .Values.platform.onCallRotationId | quote }}
{{- end }}
