apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../_base/addon-config/backstage
patches:
  - target:
      kind: HelmRelease
      name: backstage
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 3
      - op: add
        path: /spec/values/autoscaling
        value:
          enabled: true
          minReplicas: 3
          maxReplicas: 9
          targetCPUUtilizationPercentage: 70
