apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/namespace-cert-manager.yaml
  - platform/namespace-external-dns.yaml
  - platform/namespace-external-secrets.yaml
  - platform/namespace-kyverno.yaml
  - platform/namespace-azureserviceoperator-system.yaml
  - platform/namespace-keda.yaml
  - platform/namespace-ingress-nginx.yaml
  - platform/namespace-observability.yaml
  - platform/helmrepository-jetstack.yaml
  - platform/helmrepository-secrets-store-csi-driver.yaml
  - platform/helmrepository-csi-secrets-store-provider-azure.yaml
  - platform/helmrepository-external-dns.yaml
  - platform/helmrepository-external-secrets.yaml
  - platform/helmrepository-kyverno.yaml
  - platform/helmrepository-aso2.yaml
  - platform/helmrepository-kedacore.yaml
  - platform/helmrepository-ingress-nginx.yaml
  - platform/helmrepository-open-telemetry.yaml
  - platform/helmrepository-fairwinds-stable.yaml
  - platform/secrets-store-csi-driver.yaml
  - platform/csi-secrets-store-provider-azure.yaml
  - platform/external-secrets.yaml
  - platform/cert-manager.yaml
  - platform/external-dns.yaml
  - platform/kyverno.yaml
  - platform/aso.yaml
  - platform/keda.yaml
  - platform/ingress-nginx.yaml
  - platform/ama-metrics-settings-configmap.yaml
  - platform/vpa.yaml
  - platform/opentelemetry-collector.yaml
  - platform/opentelemetry-collector-node.yaml
