apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: public-backstage
  namespace: flux-system
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
  labels:
    app: backstage
    team: platform-engineering
    costCenter: cc-platform
    dataClassification: internal
spec:
  interval: 5m
  path: ./${cluster_state_root_path}/public-backstage
  postBuild:
    substitute:
      backstage_public_ingress_host: ${backstage_public_ingress_host}
  prune: true
  retryInterval: 1m
  serviceAccountName: platform-reconciler
  sourceRef:
    kind: GitRepository
    name: platform-demo
  timeout: 5m
  wait: false
